### PR TITLE
Master

### PR DESCRIPTION
**Pull request by folker**

### CODE REVIEW

**Comment by teharrison** [comment]
latex noob here.  can some tell me how to generate a pdf from the contents of this repo, I just want to read stuff.

**Comment by wilke** [comment]
Try ps2pdf

On Feb 4, 2015, at 10:06 AM, Travis Harrison <notifications@github.com<mailto:notifications@github.com>> wrote:


latex noob here. can some tell me how to generate a pdf from the contents of this repo, I just want to read stuff.

—
Reply to this email directly or view it on GitHub<https://github.com/MG-RAST/tech-report/pull/11#issuecomment-72882023>.

Andreas Wilke
Argonne National Laboratory
Mathematics and Computer Science Division
Bldg. 240 , 4F8
9700 South Cass Avenue
Argonne, IL  60439
(630) 252-3190 (phone)
(630) 252-5986.(fax)

**Comment by folker** [comment]
try texworks....

**Comment by teharrison** [comment]
Will pointed me to MacTex, which installed 4.62 GB of data on my machine :(

**Pull request merged**
